package com.views.CorePerformance;

import com.generic.Pojo;
import com.generic.Utilities;
import com.generic.WrapperFunctions;
import com.pageFactory.CorePerformance.DashboardPage;
import com.pageFactory.CorePerformance.EmployeeManagementPage;
import com.pageFactory.CorePerformance.LoginPage;

public class ViewForEmployeeManagement  {
	
	private Utilities objUtilities;
	private Pojo objPojo;
	private EmployeeManagementPage objEmployeeManagementPage;

	public ViewForEmployeeManagement(Pojo objPojo) {
		objEmployeeManagementPage = new EmployeeManagementPage(objPojo);
		objUtilities = objPojo.getObjUtilities();
	}
	
	public void clickOnEmployeeManagementTab() {
		objEmployeeManagementPage.clickOnEmployeeMngmntElement();
	}
	
//	public boolean getEmployeePageUrl() {
//		return objEmployeeManagementPage.waitForEmployeePageLoad();
//	}
	
	public void addEmployeeIcon() {
		objEmployeeManagementPage.clickOnAddEmpIcon();
	}
	
	public void addEmpDetails(String fname, String mname, String lname) {
		objEmployeeManagementPage.enterEmployeeDetails(fname, mname, lname);
	}
	
	public boolean verifyAutoGeneratedIDToggleSatus() {
		return objEmployeeManagementPage.checkAutoGenerateIDToggleIsSelected();
	}
}
