package com.scripts.CorePerformance;

import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.generic.BaseTest;
import com.generic.Pojo;
import com.views.CorePerformance.ViewForDashboard;
import com.views.CorePerformance.ViewForEmployeeManagement;

public class EmployeeManagementTest extends BaseTest{
	
	Properties objCCBProperties;
	private ViewForEmployeeManagement objViewForEmployee;
	List<String> expectedWidgetList = new ArrayList<>();
	Pojo objPojo;
	
	@BeforeClass
	public void initPageObjects() {
		objViewForEmployee = new ViewForEmployeeManagement(this);
		objCCBProperties = this.getObjConfig();
	}
	
	@Test
	public void validateEmployeeManagementModule_TC6() {
		System.out.println("STEP - Click on 'Employee Management' tab.");
		objViewForEmployee.clickOnEmployeeManagementTab();
		System.out.println("VERIFY - On clicking the 'Employee Management' tab, the user should be navigated to the 'Employee Management' page.");
		System.out.println("STEP - Click on the 'Add Employee' icon");
		objViewForEmployee.addEmployeeIcon();
		System.out.println("STEP - Enter values in the 'First Name', 'Middle Name', and 'Last Name' fields.");
		objViewForEmployee.addEmpDetails(objCCBProperties.getProperty("firstName"),objCCBProperties.getProperty("middleName"), objCCBProperties.getProperty("lastName"));
		System.out.println("VERIFY - The 'Auto Generate Employee ID' option is selected by default.");
		objViewForEmployee.verifyAutoGeneratedIDToggleSatus();
		System.out.println("STEP - Select a valid date from the 'Joined Date' calendar picker.");
		System.out.println("STEP - Select a location from the 'Location' dropdown menu.");
		System.out.println("STEP - Enter values in 'User Name' field.");
		System.out.println("STEP - Enter value in 'Password' field.");
		System.out.println("STEP - Enter value in 'Confirm Password' field.");
		System.out.println("VERIFY - 'Status' radio button is selected by default.");
	}
}